/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

//awt
import java.awt.Color;
import java.awt.event.KeyEvent;

//swing
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Richard
 */
public class BuscarCompras extends javax.swing.JDialog {

    static hetec.OracleBD oraclebd;
    static String usuario_g;
    DefaultTableModel modelo;
    int id = -1;

    /**
     * Creates new form BuscarCompras
     */
    public BuscarCompras(java.awt.Frame parent, boolean modal, hetec.OracleBD oracle, String usuario) {
        super(parent, modal);
        initComponents();
        oraclebd = oracle;
        usuario_g = usuario;
        this.setTitle("HETEC Compras Pendientes " + usuario_g);
        cargarCompras();
        CancelarBtn.requestFocus();

        /*ESTILO*/
        //POSICION DE PANTALLA
        this.setLocationRelativeTo(null);
        //FONDO
        getContentPane().setBackground(Color.WHITE);
        //BORDER
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray));
        //FONDO DE PANEL
        panel1.setBackground(Color.white);
        //FONDO TABLA
        ComprasTbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        ComprasTbl.setOpaque(true);
        ComprasTbl.setFillsViewportHeight(true);
        ComprasTbl.setBackground(Color.white);
        /*TERMINA ESTILO*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComprasTbl = new javax.swing.JTable();
        CancelarBtn = new javax.swing.JButton();
        AceptarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 550));
        setSize(new java.awt.Dimension(800, 550));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jlogo2.png"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(118, 20));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(32, 116, 174));
        jLabel25.setText("BUSCAR COMPRAS");

        ComprasTbl.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ComprasTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Transacción", "Documento", "Fecha", "Proveedor", "Nombre", "Tipo", "Detalle", "Moneda", "Valor de Cambio", "Empresa", "Localización", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ComprasTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComprasTblMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(ComprasTbl);

        CancelarBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelarBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CancelarBtn.setForeground(new java.awt.Color(32, 116, 174));
        CancelarBtn.setText("Cancelar");
        CancelarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 116, 174)));
        CancelarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarBtnMouseExited(evt);
            }
        });
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });
        CancelarBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CancelarBtnKeyPressed(evt);
            }
        });

        AceptarBtn.setBackground(new java.awt.Color(255, 255, 255));
        AceptarBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AceptarBtn.setForeground(new java.awt.Color(32, 116, 174));
        AceptarBtn.setText("Aceptar");
        AceptarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 116, 174)));
        AceptarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AceptarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AceptarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AceptarBtnMouseExited(evt);
            }
        });
        AceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtnActionPerformed(evt);
            }
        });
        AceptarBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AceptarBtnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(AceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprasTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprasTblMousePressed
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            aceptar();
        }
    }//GEN-LAST:event_ComprasTblMousePressed

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarBtnActionPerformed

    private void CancelarBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CancelarBtnKeyPressed
        this.dispose();
    }//GEN-LAST:event_CancelarBtnKeyPressed

    private void AceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtnActionPerformed
        aceptar();
    }//GEN-LAST:event_AceptarBtnActionPerformed

    private void AceptarBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AceptarBtnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            aceptar();
        }
    }//GEN-LAST:event_AceptarBtnKeyPressed

    private void CancelarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBtnMouseEntered
        CancelarBtn.setBackground(new java.awt.Color(32, 116, 174));
        CancelarBtn.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_CancelarBtnMouseEntered

    private void CancelarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBtnMouseExited
         CancelarBtn.setBackground(new java.awt.Color(255,255,255));
        CancelarBtn.setForeground(new java.awt.Color(32, 116, 174));
    }//GEN-LAST:event_CancelarBtnMouseExited

    private void AceptarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarBtnMouseEntered
        AceptarBtn.setBackground(new java.awt.Color(32, 116, 174));
        AceptarBtn.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_AceptarBtnMouseEntered

    private void AceptarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarBtnMouseExited
         AceptarBtn.setBackground(new java.awt.Color(255,255,255));
        AceptarBtn.setForeground(new java.awt.Color(32, 116, 174));
    }//GEN-LAST:event_AceptarBtnMouseExited

    //Método para el botón Aceptar.
    public void aceptar() {
        if (ComprasTbl.getSelectedRow() > -1) {
            id = (Integer) (ComprasTbl.getValueAt(ComprasTbl.getSelectedRow(), 0));
            this.dispose();
        }
    }

    //Cargar la Tabla de Compras Creadas.
    public void cargarCompras() {
        modelo = new tableModel();
        for (int i = 0; i < 12; i++) {
            modelo.addColumn(ComprasTbl.getColumnName(i));
        }
        ComprasTbl.setModel(modelo);
        configurarTabla();
        oraclebd.getComprasCreadas(modelo);
    }

    //Método para Configurar Tamaño de Columnas, Propiedad de No Cambiar Tamaño y Posición de Texto en las Celdas.
    public void configurarTabla() {
        ComprasTbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //Transaccion
        ComprasTbl.getColumn(ComprasTbl.getColumnName(0)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(0)).setResizable(false);
        //Documento        
        ComprasTbl.getColumn(ComprasTbl.getColumnName(1)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(1)).setResizable(false);
        //Fecha
        ComprasTbl.getColumn(ComprasTbl.getColumnName(2)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(2)).setResizable(false);
        //Proveedor
        ComprasTbl.getColumn(ComprasTbl.getColumnName(3)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(3)).setResizable(false);
        //Nombre
        ComprasTbl.getColumn(ComprasTbl.getColumnName(4)).setPreferredWidth(200);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(4)).setResizable(false);
        //Tipo de Transaccion
        ComprasTbl.getColumn(ComprasTbl.getColumnName(5)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(5)).setResizable(false);
        //Detalle
        ComprasTbl.getColumn(ComprasTbl.getColumnName(6)).setPreferredWidth(200);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(6)).setResizable(false);
        //Moneda
        ComprasTbl.getColumn(ComprasTbl.getColumnName(7)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(7)).setResizable(false);
        //Valor de Cambio
        ComprasTbl.getColumn(ComprasTbl.getColumnName(8)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(8)).setResizable(false);
        //Empresa
        ComprasTbl.getColumn(ComprasTbl.getColumnName(9)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(9)).setResizable(false);
        //Localizacion
        ComprasTbl.getColumn(ComprasTbl.getColumnName(10)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(10)).setResizable(false);
        //Departamento
        ComprasTbl.getColumn(ComprasTbl.getColumnName(11)).setPreferredWidth(100);
        //ComprasTbl.getColumn(ComprasTbl.getColumnName(11)).setResizable(false);
    }

    public int getId() {
        return id;
    }

    public class tableModel extends DefaultTableModel {

        tableModel() {

        }

        @Override
        public boolean isCellEditable(int row, int cols) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarCompras dialog = new BuscarCompras(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBtn;
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JTable ComprasTbl;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
