/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import hetec.Item;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import org.apache.commons.lang3.StringUtils;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.math.NumberUtils;

/**
 *
 * @author Richard
 */
public class CrearCliente extends javax.swing.JDialog {

    static int codigo;
    static int empresa_v;
    static hetec.OracleBD oraclebd;
    static String usuario_g;

    /**
     * Creates new form CrearArticulo
     */
    public CrearCliente(java.awt.Frame parent, boolean modal, hetec.OracleBD oracle, int empresa, String usuario) {
        super(parent, modal);
        initComponents();
        oraclebd = oracle;
        usuario_g = usuario;
        this.setTitle("HETEC Crear Cliente " + usuario_g);
        empresa_v = empresa;

        /*ESTILO*/
        //POSITION DE PANTALLA
        this.setLocationRelativeTo(null);
        //FONDO
        getContentPane().setBackground(Color.WHITE);
        //BORDE
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray));
        
        /*TERMINA ESTILO*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoDocBG = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        DocumentoTxt = new javax.swing.JTextField();
        CorreoTxt = new javax.swing.JTextField();
        TelefonosTxt = new javax.swing.JTextField();
        DireccionTxt = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CedFisicaRB = new javax.swing.JRadioButton();
        CedJuridicaRB = new javax.swing.JRadioButton();
        DimexRB = new javax.swing.JRadioButton();
        NiteRB = new javax.swing.JRadioButton();
        CancelarBtn = new javax.swing.JButton();
        AceptarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 564));
        setSize(new java.awt.Dimension(800, 550));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Tipo Documento:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Nro Documento:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Telefonos:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Direccion:");

        NombreTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreTxtKeyPressed(evt);
            }
        });

        DocumentoTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        DocumentoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DocumentoTxtKeyPressed(evt);
            }
        });

        CorreoTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        CorreoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CorreoTxtKeyPressed(evt);
            }
        });

        TelefonosTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TelefonosTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelefonosTxtKeyPressed(evt);
            }
        });

        DireccionTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(32, 116, 174));
        jLabel25.setText("CREAR CLIENTE");
        jLabel25.setToolTipText("");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jlogo2.png"))); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(118, 20));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(587, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CedFisicaRB.setBackground(new java.awt.Color(255, 255, 255));
        TipoDocBG.add(CedFisicaRB);
        CedFisicaRB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        CedFisicaRB.setText("Cedula Fisica");

        CedJuridicaRB.setBackground(new java.awt.Color(255, 255, 255));
        TipoDocBG.add(CedJuridicaRB);
        CedJuridicaRB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        CedJuridicaRB.setText("Cedula Juridica");

        DimexRB.setBackground(new java.awt.Color(255, 255, 255));
        TipoDocBG.add(DimexRB);
        DimexRB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        DimexRB.setText("DIMEX");

        NiteRB.setBackground(new java.awt.Color(255, 255, 255));
        TipoDocBG.add(NiteRB);
        NiteRB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NiteRB.setText("NITE");

        CancelarBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelarBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CancelarBtn.setForeground(new java.awt.Color(32, 116, 174));
        CancelarBtn.setText("Cancelar");
        CancelarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 116, 174)));
        CancelarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarBtnMouseExited(evt);
            }
        });

        AceptarBtn.setBackground(new java.awt.Color(255, 255, 255));
        AceptarBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AceptarBtn.setForeground(new java.awt.Color(32, 116, 174));
        AceptarBtn.setText("Aceptar");
        AceptarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 116, 174)));
        AceptarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AceptarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AceptarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CedFisicaRB)
                                .addGap(10, 10, 10)
                                .addComponent(CedJuridicaRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DimexRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NiteRB))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DocumentoTxt)
                                .addComponent(TelefonosTxt)
                                .addComponent(NombreTxt)
                                .addComponent(CorreoTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DireccionTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CedFisicaRB)
                    .addComponent(CedJuridicaRB)
                    .addComponent(DimexRB)
                    .addComponent(NiteRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DocumentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorreoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarBtnMouseClicked

    private void AceptarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarBtnMouseClicked
        // TODO add your handling code here:
        crearCliente();
    }//GEN-LAST:event_AceptarBtnMouseClicked

    private void NombreTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DocumentoTxt.requestFocus();
        }
    }//GEN-LAST:event_NombreTxtKeyPressed

    private void DocumentoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DocumentoTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CorreoTxt.requestFocus();
        }
    }//GEN-LAST:event_DocumentoTxtKeyPressed

    private void CorreoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TelefonosTxt.requestFocus();
        }
    }//GEN-LAST:event_CorreoTxtKeyPressed

    private void TelefonosTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonosTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DireccionTxt.requestFocus();
        }
    }//GEN-LAST:event_TelefonosTxtKeyPressed

    private void AceptarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarBtnMouseEntered
        AceptarBtn.setBackground(new java.awt.Color(32, 116, 174));
        AceptarBtn.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_AceptarBtnMouseEntered

    private void AceptarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarBtnMouseExited
        AceptarBtn.setBackground(new java.awt.Color(255, 255, 255));
        AceptarBtn.setForeground(new java.awt.Color(32, 116, 174));
    }//GEN-LAST:event_AceptarBtnMouseExited

    private void CancelarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBtnMouseEntered
        CancelarBtn.setBackground(new java.awt.Color(32, 116, 174));
        CancelarBtn.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_CancelarBtnMouseEntered

    private void CancelarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBtnMouseExited
        CancelarBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelarBtn.setForeground(new java.awt.Color(32, 116, 174));
    }//GEN-LAST:event_CancelarBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearCliente dialog = new CrearCliente(new javax.swing.JFrame(), true, null, -1, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void crearCliente() {
        if (StringUtils.isEmpty(NombreTxt.getText())) {
            JOptionPane.showMessageDialog(null, "Indique Nombre", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }
        if (StringUtils.isEmpty(DocumentoTxt.getText())) {
            JOptionPane.showMessageDialog(null, "Indique Documento", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }
        if (StringUtils.isEmpty(CorreoTxt.getText())) {
            JOptionPane.showMessageDialog(null, "Indique Correo", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }
        String tipodoc = "";
        if (CedFisicaRB.isSelected()) {
            tipodoc = "01";
        } else if (CedJuridicaRB.isSelected()) {
            tipodoc = "02";
        } else if (DimexRB.isSelected()) {
            tipodoc = "03";
        } else if (NiteRB.isSelected()) {
            tipodoc = "04";
        } else {
            JOptionPane.showMessageDialog(null, "Indique Tipo Documento", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }

        codigo = oraclebd.crearCliente(NombreTxt.getText(), tipodoc, DocumentoTxt.getText(), null,
                TelefonosTxt.getText(), DireccionTxt.getText(), "N", CorreoTxt.getText(),
                "", "S", "N");
        this.dispose();
    }

    public int getCodigo() {
        return codigo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBtn;
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JRadioButton CedFisicaRB;
    private javax.swing.JRadioButton CedJuridicaRB;
    private javax.swing.JTextField CorreoTxt;
    private javax.swing.JRadioButton DimexRB;
    private javax.swing.JTextField DireccionTxt;
    private javax.swing.JTextField DocumentoTxt;
    private javax.swing.JRadioButton NiteRB;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField TelefonosTxt;
    private javax.swing.ButtonGroup TipoDocBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
