/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

//awt
import java.awt.Color;
import java.awt.event.KeyEvent;

//swing
import javax.swing.BorderFactory;

//text
import java.text.NumberFormat;

//util
import org.apache.commons.lang3.math.NumberUtils;

//Propios
import hetec.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Richard
 */
public class PagoContado extends javax.swing.JDialog {

    static hetec.OracleBD oraclebd;
    static String usuario_g;
    static int facid;
    static Double total_p;
    static NumberFormat formatoNumero;
    /**
     * Creates new form PagoContado
     */
    public PagoContado(java.awt.Frame parent, boolean modal, hetec.OracleBD oracle, int factura, int empresa, String usuario) {
        super(parent, modal);
        initComponents();
        formatoNumero= NumberFormat.getNumberInstance();
        oraclebd = oracle;
        usuario_g = usuario;
        facid = factura;
        total_p = oraclebd.getTotalFac(factura);
        TotalTxt.setText(String.valueOf(formatoNumero.format(total_p)));
        calculavuelto();
        EfectivoTxt.requestFocus();
        oraclebd.getMonedaPago(MonedaCB, empresa, factura);
        int base_v;
        base_v = oraclebd.getMonedaBase(empresa);
        Item item;
        item = (Item) MonedaCB.getSelectedItem();
        int moneda_v = item.getId();
        CambioTxt.setText(String.valueOf(oraclebd.getCambio(moneda_v, base_v)));

        /*ESTILO*/
        //SETEA COLOR NARANJA EN VARIABLE
        Color ivory = new Color(255, 120, 0);
        //POSITION DE PANTALLA
        this.setLocationRelativeTo(null);
        //FONDO
        getContentPane().setBackground(Color.WHITE);
        //BORDE
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray));
        
        /*TERMINA ESTILO*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TotalTxt = new javax.swing.JTextField();
        jLabelEfectivo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTarjeta = new javax.swing.JLabel();
        jLabelCheque = new javax.swing.JLabel();
        jLabelNotaCredito = new javax.swing.JLabel();
        jLabelDeposito = new javax.swing.JLabel();
        jLabelDocumento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EfectivoTxt = new javax.swing.JTextField();
        OtrosTxt = new javax.swing.JTextField();
        TarjetaTxt = new javax.swing.JTextField();
        ChequeTxt = new javax.swing.JTextField();
        NotaTxt = new javax.swing.JTextField();
        DepositoTxt = new javax.swing.JTextField();
        NumeroTxt = new javax.swing.JTextField();
        VueltoTxt = new javax.swing.JTextField();
        MonedaCB = new javax.swing.JComboBox();
        CambioTxt = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 550));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Total");

        TotalTxt.setEditable(false);
        TotalTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabelEfectivo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelEfectivo.setText("Monto Efectivo");
        jLabelEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEfectivoMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Monto Efectivo Otros");

        jLabelTarjeta.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelTarjeta.setText("Monto Tarjeta");
        jLabelTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTarjetaMouseClicked(evt);
            }
        });

        jLabelCheque.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelCheque.setText("Monto Cheque");
        jLabelCheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelChequeMouseClicked(evt);
            }
        });

        jLabelNotaCredito.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelNotaCredito.setText("Monto Nota Credito");
        jLabelNotaCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNotaCreditoMouseClicked(evt);
            }
        });

        jLabelDeposito.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelDeposito.setText("Monto Deposito");
        jLabelDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDepositoMouseClicked(evt);
            }
        });

        jLabelDocumento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelDocumento.setText("Numero Documento");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Vuelto");

        EfectivoTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        EfectivoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EfectivoTxtKeyPressed(evt);
            }
        });

        OtrosTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        OtrosTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OtrosTxtKeyPressed(evt);
            }
        });

        TarjetaTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TarjetaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TarjetaTxtKeyPressed(evt);
            }
        });

        ChequeTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChequeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ChequeTxtKeyPressed(evt);
            }
        });

        NotaTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NotaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NotaTxtKeyPressed(evt);
            }
        });

        DepositoTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        DepositoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DepositoTxtKeyPressed(evt);
            }
        });

        NumeroTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        VueltoTxt.setEditable(false);
        VueltoTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        MonedaCB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        MonedaCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CambioTxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        CambioTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CambioTxtKeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(32, 116, 174));
        jLabel25.setText("PAGO CONTADO");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jlogo2.png"))); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(118, 20));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        BtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(32, 116, 174));
        BtnAceptar.setText("C/ Impresion");
        BtnAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 116, 174)));
        BtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseExited(evt);
            }
        });

        BtnImprimir.setBackground(new java.awt.Color(255, 255, 255));
        BtnImprimir.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BtnImprimir.setForeground(new java.awt.Color(32, 116, 174));
        BtnImprimir.setText("S/ Impresion");
        BtnImprimir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 116, 174)));
        BtnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnImprimirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnImprimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnImprimirMouseExited(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(32, 116, 174));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 116, 174)));
        BtnCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseDragged(evt);
            }
        });
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabelDocumento)
                    .addComponent(jLabelDeposito)
                    .addComponent(jLabelNotaCredito)
                    .addComponent(jLabelCheque)
                    .addComponent(jLabelTarjeta)
                    .addComponent(jLabel3)
                    .addComponent(jLabelEfectivo)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VueltoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepositoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChequeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TarjetaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OtrosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EfectivoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(MonedaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CambioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEfectivo)
                    .addComponent(EfectivoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(OtrosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonedaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTarjeta)
                    .addComponent(TarjetaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelCheque)
                    .addComponent(ChequeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelNotaCredito)
                    .addComponent(NotaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelDeposito)
                    .addComponent(DepositoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelDocumento)
                    .addComponent(NumeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(VueltoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EfectivoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EfectivoTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculavuelto();
            OtrosTxt.requestFocus();
        }
    }//GEN-LAST:event_EfectivoTxtKeyPressed

    private void OtrosTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OtrosTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculavuelto();
            CambioTxt.requestFocus();
        }
    }//GEN-LAST:event_OtrosTxtKeyPressed

    private void CambioTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CambioTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculavuelto();
            TarjetaTxt.requestFocus();
        }
    }//GEN-LAST:event_CambioTxtKeyPressed

    private void TarjetaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TarjetaTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculavuelto();
            ChequeTxt.requestFocus();
        }
    }//GEN-LAST:event_TarjetaTxtKeyPressed

    private void ChequeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChequeTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculavuelto();
            NotaTxt.requestFocus();
        }
    }//GEN-LAST:event_ChequeTxtKeyPressed

    private void NotaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NotaTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculavuelto();
            DepositoTxt.requestFocus();
        }
    }//GEN-LAST:event_NotaTxtKeyPressed

    private void DepositoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DepositoTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculavuelto();
            NumeroTxt.requestFocus();
        }
    }//GEN-LAST:event_DepositoTxtKeyPressed

    private void BtnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseClicked
        regPago();
        oraclebd.imprimirFactura(facid);
        this.dispose();
    }//GEN-LAST:event_BtnAceptarMouseClicked

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnCancelarMouseClicked

    private void BtnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseEntered
        BtnAceptar.setBackground(new java.awt.Color(32, 116, 174));
        BtnAceptar.setForeground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAceptarMouseEntered

    private void BtnCancelarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseDragged
       // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarMouseDragged

    private void BtnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseEntered
        BtnCancelar.setBackground(new java.awt.Color(32, 116, 174));
        BtnCancelar.setForeground(new java.awt.Color(255,255,255)); 
    }//GEN-LAST:event_BtnCancelarMouseEntered

    private void BtnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseExited
        BtnCancelar.setBackground(new java.awt.Color(255,255,255));
        BtnCancelar.setForeground(new java.awt.Color(32, 116, 174));    
    }//GEN-LAST:event_BtnCancelarMouseExited

    private void BtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseExited
        BtnAceptar.setBackground(new java.awt.Color(255,255,255));
        BtnAceptar.setForeground(new java.awt.Color(32, 116, 174)); 
    }//GEN-LAST:event_BtnAceptarMouseExited

    private void BtnImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnImprimirMouseClicked
        // TODO add your handling code here:
        regPago();
        this.dispose();        
    }//GEN-LAST:event_BtnImprimirMouseClicked

    private void BtnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnImprimirMouseEntered
        // TODO add your handling code here:
        BtnAceptar.setBackground(new java.awt.Color(32, 116, 174));
        BtnAceptar.setForeground(new java.awt.Color(255,255,255));        // TODO add your handling code here:        
    }//GEN-LAST:event_BtnImprimirMouseEntered

    private void BtnImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnImprimirMouseExited
        // TODO add your handling code here:
        BtnAceptar.setBackground(new java.awt.Color(255,255,255));
        BtnAceptar.setForeground(new java.awt.Color(32, 116, 174));         
    }//GEN-LAST:event_BtnImprimirMouseExited
//Click en el label para autorellenar el monto
    private void jLabelEfectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEfectivoMouseClicked
        // TODO add your handling code here:
        EfectivoTxt.setText(String.valueOf(formatoNumero.format(total_p)));
        calculavuelto();
        EfectivoTxt.requestFocus();
    }//GEN-LAST:event_jLabelEfectivoMouseClicked

    private void jLabelTarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTarjetaMouseClicked
        // TODO add your handling code here:
        TarjetaTxt.setText(String.valueOf(formatoNumero.format(total_p)));
        calculavuelto();
        EfectivoTxt.requestFocus();
    }//GEN-LAST:event_jLabelTarjetaMouseClicked

    private void jLabelChequeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelChequeMouseClicked
        // TODO add your handling code here:
        ChequeTxt.setText(String.valueOf(formatoNumero.format(total_p)));
        calculavuelto();
        ChequeTxt.requestFocus();
    }//GEN-LAST:event_jLabelChequeMouseClicked

    private void jLabelNotaCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNotaCreditoMouseClicked
        // TODO add your handling code here:
        NotaTxt.setText(String.valueOf(formatoNumero.format(total_p)));
        calculavuelto();
        NotaTxt.requestFocus();
    }//GEN-LAST:event_jLabelNotaCreditoMouseClicked

    private void jLabelDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDepositoMouseClicked
        // TODO add your handling code here:
        DepositoTxt.setText(String.valueOf(formatoNumero.format(total_p)));
        calculavuelto();
        DepositoTxt.requestFocus();
    }//GEN-LAST:event_jLabelDepositoMouseClicked

    public void regPago(){
            // TODO add your handling code here:
        Double efectivo_v = 0.0, otros_v = 0.0, cambio_v = 0.0, tarjeta_v = 0.0, cheque_v = 0.0, nota_v = 0.0, deposito_v = 0.0, total_v = 0.0;
        if (!EfectivoTxt.getText().isEmpty() && NumberUtils.isNumber(EfectivoTxt.getText())) {
            efectivo_v = Double.parseDouble(EfectivoTxt.getText());
        }
        if (!OtrosTxt.getText().isEmpty() && NumberUtils.isNumber(OtrosTxt.getText())) {
            otros_v = Double.parseDouble(OtrosTxt.getText());
        }
        if (!CambioTxt.getText().isEmpty() && NumberUtils.isNumber(CambioTxt.getText())) {
            cambio_v = Double.parseDouble(CambioTxt.getText());
        }
        if (!TarjetaTxt.getText().isEmpty() && NumberUtils.isNumber(TarjetaTxt.getText())) {
            tarjeta_v = Double.parseDouble(TarjetaTxt.getText());
        }
        if (!ChequeTxt.getText().isEmpty() && NumberUtils.isNumber(ChequeTxt.getText())) {
            cheque_v = Double.parseDouble(ChequeTxt.getText());
        }
        if (!NotaTxt.getText().isEmpty() && NumberUtils.isNumber(NotaTxt.getText())) {
            nota_v = Double.parseDouble(NotaTxt.getText());
        }
        if (!DepositoTxt.getText().isEmpty() && NumberUtils.isNumber(DepositoTxt.getText())) {
            deposito_v = Double.parseDouble(DepositoTxt.getText());
        }
        Item item;
        item = (Item) MonedaCB.getSelectedItem();
        int moneda_v = item.getId();
        oraclebd.cancelaFactura(facid, efectivo_v,
                otros_v, moneda_v,
                cambio_v, tarjeta_v,
                cheque_v, nota_v,
                deposito_v, NumeroTxt.getText());
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoContado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoContado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoContado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoContado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagoContado dialog = new PagoContado(new javax.swing.JFrame(), true, null, -1, -1, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void calculavuelto() {
        NumberFormat formatoNumero = NumberFormat.getNumberInstance();
        Double efectivo_v = 0.0, otros_v = 0.0, cambio_v = 0.0, tarjeta_v = 0.0, cheque_v = 0.0, nota_v = 0.0, deposito_v = 0.0, total_v = 0.0;
        if (!EfectivoTxt.getText().isEmpty() && NumberUtils.isNumber(EfectivoTxt.getText())) {
            efectivo_v = Double.parseDouble(EfectivoTxt.getText());
        }
        if (!OtrosTxt.getText().isEmpty() && NumberUtils.isNumber(OtrosTxt.getText())) {
            otros_v = Double.parseDouble(OtrosTxt.getText());
        }
        if (!CambioTxt.getText().isEmpty() && NumberUtils.isNumber(CambioTxt.getText())) {
            cambio_v = Double.parseDouble(CambioTxt.getText());
        }
        if (!TarjetaTxt.getText().isEmpty() && NumberUtils.isNumber(TarjetaTxt.getText())) {
            tarjeta_v = Double.parseDouble(TarjetaTxt.getText());
        }
        if (!ChequeTxt.getText().isEmpty() && NumberUtils.isNumber(ChequeTxt.getText())) {
            cheque_v = Double.parseDouble(ChequeTxt.getText());
        }
        if (!NotaTxt.getText().isEmpty() && NumberUtils.isNumber(NotaTxt.getText())) {
            nota_v = Double.parseDouble(NotaTxt.getText());
        }
        if (!DepositoTxt.getText().isEmpty() && NumberUtils.isNumber(DepositoTxt.getText())) {
            deposito_v = Double.parseDouble(DepositoTxt.getText());
        }
        Double vuelto_v = efectivo_v
                + (otros_v * cambio_v)
                + tarjeta_v
                + cheque_v
                + nota_v
                + deposito_v
                - total_p;
        VueltoTxt.setText(String.valueOf(formatoNumero.format(vuelto_v)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JTextField CambioTxt;
    private javax.swing.JTextField ChequeTxt;
    private javax.swing.JTextField DepositoTxt;
    private javax.swing.JTextField EfectivoTxt;
    private javax.swing.JComboBox MonedaCB;
    private javax.swing.JTextField NotaTxt;
    private javax.swing.JTextField NumeroTxt;
    private javax.swing.JTextField OtrosTxt;
    private javax.swing.JTextField TarjetaTxt;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JTextField VueltoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCheque;
    private javax.swing.JLabel jLabelDeposito;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelEfectivo;
    private javax.swing.JLabel jLabelNotaCredito;
    private javax.swing.JLabel jLabelTarjeta;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
